// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiwssfnqdxvrkdkdxhms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppd3NzZm5xZHh2cmtka2R4aG1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDcxMjcsImV4cCI6MjA2NjQyMzEyN30.ZMqkEiTgjWiZuG9tL8DLJrwQJvONVgeV8WLW3IszUP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);